name: Sync Prisma Schema

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check out schema repository
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Copy Schema to Frontend Repository
      run: |
        git clone https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/alienbuild/mintalysis_frontend.git
        cp prisma/schema.prisma mintalysis_frontend/prisma/schema.prisma
        cd mintalysis_frontend
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add .
        git commit -m 'Update Prisma Schema'
        git push
    
    - name: Copy Schema to Backend Repository
      run: |
        git clone https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/alienbuild/mintalysis_backend.git
        cp prisma/schema.prisma mintalysis_backend/prisma/schema.prisma
        cd mintalysis_backend
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add .
        git commit -m 'Update Prisma Schema'
        git push

    - name: Copy Schema to Services Repository
      run: |
        git clone https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/alienbuild/mintalysis_services.git
        cp prisma/schema.prisma mintalysis_services/prisma/schema.prisma
        cd mintalysis_services
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add .
        git commit -m 'Update Prisma Schema'
        git push
